### ISSUE TITLE
Distributed Data Parallel training with Pytorch Lightning (PL) and Sagemaker

### ISSUE THREAD

**Issue by shubhamwagh** [mattreid9956/plightning#1]
Hi, may I know where do you use your custom `smdistributed_ddp_accelerator.py` script?

Can you outline the steps required to perform distributed parallel training using multiple sagemaker training instances for PL framework?

Does Sagemaker handle it automatically for us? or some settings are required in PL script as well?

Thanks.

**Comment by mattreid9956** [comment]
It’s not used, this is really just a toy repo, never intended anyone to actually ask me about it lol.
However SM will do some of the work for you, the train.py and main.py should be enough of an example. But I don’t use the smdistributed ddp from the sagemaker team, apparently pytorch-lightning team are working to add this though
